sudo: required
services:
  - docker

before_install:
  - docker build -t tldevoteam/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true tldevoteam/react-test npm test

after_success:
  - docker build -t tldevoteam/multi-client ./client
  - docker build -t tldevoteam/multi-nginx ./nginx
  - docker build -t tldevoteam/multi-server ./server
  - docker build -t tldevoteam/multi-worker ./worker

  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push these images to docker hub
  - docker push tldevoteam/multi-client
  - docker push tldevoteam/multi-nginx
  - docker push tldevoteam/multi-server
  - docker push tldevoteam/multi-worker

